# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
# check this on https://fabricmc.net/versions.html
minecraft_version=26.2
loader_version=0.19.3

# Mod Properties
mod_version = 3.2.1
maven_group = dev.lambdacraft
archives_base_name = fabric-per-player-spawns